/**
 * The machine-readable ontology registry.
 *
 * This is the contract `validate:ontology` enforces. Every edge type declares
 * its allowed node pairs, its single canonical direction, cardinality, temporal
 * overlap rule, evidence and confidence requirements, and the Lapemo record that
 * owns the relationship when one exists.
 *
 * `lapemoSourceOfTruth` is the load-bearing field. When it is set, the edge is a
 * DERIVED PROJECTION: Lapemo owns the writable truth and this package must never
 * treat the edge as authoritative to write back. When it is null, the edge is
 * canonical in the graph because no other system models the relationship at all.
 */

import type { RelationshipContract } from '../edges/index.js'
import { EDGE_TYPES, type EdgeType } from '../edges/index.js'
import type { NodeType } from '../enums/index.js'

export const RELATIONSHIP_CONTRACTS: readonly RelationshipContract[] = [
  // ── Structure and identity ────────────────────────────────────────────────
  {
    edgeType: 'PART_OF',
    allowedSourceTypes: ['OrganizationalUnit', 'Person', 'Role'],
    allowedTargetTypes: ['Organization', 'OrganizationalUnit'],
    direction: 'PART_OF always points from the contained node to its container.',
    cardinality: 'MANY_TO_ONE',
    allowsTemporalOverlap: false,
    requiresEvidence: false,
    minimumConfidence: null,
    lapemoSourceOfTruth: { Person: 'Person.teamId and Person.businessUnitId', OrganizationalUnit: 'OwnershipRecord.parentRecordId' },
    notes: 'Single structural containment direction. There is deliberately no PARENT_OF inverse.',
  },
  {
    edgeType: 'ASSIGNED_TO',
    allowedSourceTypes: ['RoleAssignment'],
    allowedTargetTypes: ['Person'],
    direction: 'ASSIGNED_TO points from the role assignment to the person holding it.',
    cardinality: 'MANY_TO_ONE',
    allowsTemporalOverlap: false,
    requiresEvidence: false,
    minimumConfidence: null,
    lapemoSourceOfTruth: null,
    notes: 'Temporal role assignment does not exist as a first-class Lapemo record.',
  },
  {
    edgeType: 'OCCUPIES',
    allowedSourceTypes: ['Person'],
    allowedTargetTypes: ['Role'],
    direction: 'OCCUPIES points from the person to the role they hold.',
    cardinality: 'MANY_TO_MANY',
    allowsTemporalOverlap: true,
    requiresEvidence: false,
    minimumConfidence: null,
    lapemoSourceOfTruth: { Person: 'Person.role, Person.title and OrganizationMember.role, all loose strings' },
    notes: 'Lapemo has no first-class Role model; the projection is lossy and is recorded as IB-005.',
  },
  {
    edgeType: 'REPORTS_TO',
    allowedSourceTypes: ['Person'],
    allowedTargetTypes: ['Person'],
    direction: 'REPORTS_TO points from the report to the manager.',
    cardinality: 'MANY_TO_ONE',
    allowsTemporalOverlap: false,
    requiresEvidence: false,
    minimumConfidence: null,
    lapemoSourceOfTruth: { Person: 'Person.managerId' },
    notes: 'Line management, which is distinct from supervision of a governed agent.',
  },

  // ── Ownership and supervision ─────────────────────────────────────────────
  {
    edgeType: 'OWNS',
    allowedSourceTypes: ['Person'],
    allowedTargetTypes: ['EnterpriseSystem', 'InformationAsset', 'Control', 'Policy', 'OrganizationalUnit'],
    direction: 'OWNS always points from the owning Person to the owned node.',
    cardinality: 'EXACTLY_ONE_ACTIVE_INBOUND',
    allowsTemporalOverlap: false,
    requiresEvidence: false,
    minimumConfidence: null,
    lapemoSourceOfTruth: { Person: 'OwnershipRecord.driId' },
    notes: 'Single named owner. Joint ownership is rejected at the domain layer.',
  },
  {
    edgeType: 'ACCOUNTABLE_FOR',
    allowedSourceTypes: ['Person'],
    allowedTargetTypes: ['Agent', 'Outcome', 'DecisionEvent'],
    direction: 'ACCOUNTABLE_FOR always points from the accountable Person to the node they answer for.',
    cardinality: 'EXACTLY_ONE_ACTIVE_INBOUND',
    allowsTemporalOverlap: false,
    requiresEvidence: false,
    minimumConfidence: null,
    lapemoSourceOfTruth: { Person: 'OwnershipRecord where entityType is AGENT, driId, status ACTIVE' },
    notes: 'Substrate for AUTH-001. Exactly one active accountable Person, never a role, team or system.',
  },
  {
    edgeType: 'SUPERVISES',
    allowedSourceTypes: ['Person'],
    allowedTargetTypes: ['Agent'],
    direction: 'SUPERVISES always points from the supervising Person to the governed agent.',
    cardinality: 'EXACTLY_ONE_ACTIVE_INBOUND',
    allowsTemporalOverlap: false,
    requiresEvidence: false,
    minimumConfidence: null,
    lapemoSourceOfTruth: { Person: 'Agent.supervisorId, required and non-nullable' },
    notes: 'Substrate for AUTH-002 and the structural facts behind Supervisory Control Capacity.',
  },
  {
    edgeType: 'OPERATES',
    allowedSourceTypes: ['Agent'],
    allowedTargetTypes: ['EnterpriseSystem'],
    direction: 'OPERATES points from the governed agent to the system it operates within.',
    cardinality: 'MANY_TO_MANY',
    allowsTemporalOverlap: true,
    requiresEvidence: false,
    minimumConfidence: null,
    lapemoSourceOfTruth: { Agent: 'Agent.authorizedPlatforms' },
    notes: '',
  },
  {
    edgeType: 'SPONSORS',
    allowedSourceTypes: ['Role'],
    allowedTargetTypes: ['Agent'],
    direction: 'SPONSORS points from the sponsoring role to the governed agent.',
    cardinality: 'MANY_TO_ONE',
    allowsTemporalOverlap: false,
    requiresEvidence: false,
    minimumConfidence: null,
    lapemoSourceOfTruth: null,
    notes: 'No Lapemo equivalent exists.',
  },
  {
    edgeType: 'TECHNICALLY_OWNS',
    allowedSourceTypes: ['Person'],
    allowedTargetTypes: ['Agent', 'EnterpriseSystem'],
    direction: 'TECHNICALLY_OWNS points from the technical owner to the node they maintain.',
    cardinality: 'EXACTLY_ONE_ACTIVE_INBOUND',
    allowsTemporalOverlap: false,
    requiresEvidence: false,
    minimumConfidence: null,
    lapemoSourceOfTruth: null,
    notes: 'Technical ownership is maintenance responsibility. It is never accountability and never authority.',
  },

  // ── Authority ─────────────────────────────────────────────────────────────
  {
    edgeType: 'GRANTS',
    allowedSourceTypes: ['Person', 'Role'],
    allowedTargetTypes: ['AuthorityGrant'],
    direction: 'GRANTS points from the granting actor to the authority grant they issued.',
    cardinality: 'MANY_TO_MANY',
    allowsTemporalOverlap: true,
    requiresEvidence: true,
    minimumConfidence: null,
    lapemoSourceOfTruth: null,
    notes: 'Graph canonical. No authority grant concept exists anywhere in the Lapemo ecosystem.',
  },
  {
    edgeType: 'AUTHORIZES',
    allowedSourceTypes: ['AuthorityGrant'],
    allowedTargetTypes: ['Agent', 'Person'],
    direction: 'AUTHORIZES points from the authority grant to the actor it empowers.',
    cardinality: 'MANY_TO_MANY',
    allowsTemporalOverlap: true,
    requiresEvidence: false,
    minimumConfidence: null,
    lapemoSourceOfTruth: null,
    notes: 'AgentDecisionAuth is a boolean pair only and cannot express limits, scope or period.',
  },
  {
    edgeType: 'COVERS',
    allowedSourceTypes: ['AuthorityGrant', 'Policy', 'Control'],
    allowedTargetTypes: ['DecisionType'],
    direction: 'COVERS points from the governing node to the decision type it covers.',
    cardinality: 'MANY_TO_MANY',
    allowsTemporalOverlap: true,
    requiresEvidence: false,
    minimumConfidence: null,
    lapemoSourceOfTruth: { Control: 'GovernanceControl.decisionTypeId' },
    notes: 'Generic name, explicit node pairs. Scope of applicability, never scope of permission.',
  },
  {
    edgeType: 'LIMITED_TO',
    allowedSourceTypes: ['AuthorityGrant', 'SystemPermission'],
    allowedTargetTypes: ['EnterpriseSystem', 'OrganizationalUnit'],
    direction: 'LIMITED_TO points from the bounded node to the boundary it may not exceed.',
    cardinality: 'MANY_TO_MANY',
    allowsTemporalOverlap: true,
    requiresEvidence: false,
    minimumConfidence: null,
    lapemoSourceOfTruth: null,
    notes: 'Expresses scope restriction. Absence of the edge means unrestricted, which is recorded explicitly.',
  },
  {
    edgeType: 'REQUIRES_REVIEW_BY',
    allowedSourceTypes: ['AuthorityGrant', 'DecisionType', 'Policy', 'Exception'],
    allowedTargetTypes: ['Person', 'Role'],
    direction: 'REQUIRES_REVIEW_BY points from the requiring node to the reviewer.',
    cardinality: 'MANY_TO_MANY',
    allowsTemporalOverlap: true,
    requiresEvidence: false,
    minimumConfidence: null,
    lapemoSourceOfTruth: null,
    notes: '',
  },
  {
    edgeType: 'DERIVED_FROM',
    allowedSourceTypes: ['AuthorityGrant'],
    allowedTargetTypes: ['AuthorityGrant', 'Policy', 'Role'],
    direction: 'DERIVED_FROM points from the delegated grant to the source it was delegated from.',
    cardinality: 'MANY_TO_ONE',
    allowsTemporalOverlap: false,
    requiresEvidence: true,
    minimumConfidence: null,
    lapemoSourceOfTruth: null,
    notes: 'The delegation chain AUTH-012 walks. A chain must terminate at an organizational source.',
  },
  {
    edgeType: 'SUPERSEDES',
    allowedSourceTypes: [
      'AuthorityGrant', 'AutonomyState', 'Policy', 'Control', 'DecisionType',
      'Agent', 'Person', 'InformationAsset', 'SystemPermission', 'Outcome',
    ],
    allowedTargetTypes: [
      'AuthorityGrant', 'AutonomyState', 'Policy', 'Control', 'DecisionType',
      'Agent', 'Person', 'InformationAsset', 'SystemPermission', 'Outcome',
    ],
    direction: 'SUPERSEDES points from the successor version to the predecessor version.',
    cardinality: 'EXACTLY_ONE_ACTIVE_OUTBOUND',
    allowsTemporalOverlap: false,
    requiresEvidence: false,
    minimumConfidence: null,
    lapemoSourceOfTruth: { DecisionType: 'DecisionType.supersededById', Control: 'GovernanceControl.supersededById', InformationAsset: 'KnowledgeDomain.supersededById' },
    notes: 'Append-only supersede lineage. The predecessor is closed in the same operation, never deleted.',
  },
  {
    edgeType: 'REVOKES',
    allowedSourceTypes: ['Person', 'Policy'],
    allowedTargetTypes: ['AuthorityGrant', 'SystemPermission'],
    direction: 'REVOKES points from the revoking actor or policy to the revoked grant.',
    cardinality: 'MANY_TO_MANY',
    allowsTemporalOverlap: true,
    requiresEvidence: true,
    minimumConfidence: null,
    lapemoSourceOfTruth: null,
    notes: 'Revocation is an event with lineage. It never deletes the grant it revokes.',
  },

  // ── Permission, technical and never organizational ────────────────────────
  {
    edgeType: 'HAS_PERMISSION',
    allowedSourceTypes: ['Agent', 'Person'],
    allowedTargetTypes: ['SystemPermission'],
    direction: 'HAS_PERMISSION points from the principal actor to the technical permission it holds.',
    cardinality: 'MANY_TO_MANY',
    allowsTemporalOverlap: true,
    requiresEvidence: false,
    minimumConfidence: null,
    lapemoSourceOfTruth: { Agent: 'ConnectorCapabilityGrant and ConnectorDataAccessGrant, connector scoped', Person: 'ConnectorCapabilityGrant and ConnectorDataAccessGrant, connector scoped' },
    notes: 'Technical permission. This edge NEVER establishes organizational authority.',
  },
  {
    edgeType: 'PERMITS_IN',
    allowedSourceTypes: ['SystemPermission'],
    allowedTargetTypes: ['EnterpriseSystem'],
    direction: 'PERMITS_IN points from the technical permission to the system that honors it.',
    cardinality: 'MANY_TO_ONE',
    allowsTemporalOverlap: false,
    requiresEvidence: false,
    minimumConfidence: null,
    lapemoSourceOfTruth: { SystemPermission: 'ConnectorInstance to IntegrationDefinition' },
    notes: '',
  },

  // ── Decision and execution ────────────────────────────────────────────────
  {
    edgeType: 'INITIATES',
    allowedSourceTypes: ['Person', 'Agent'],
    allowedTargetTypes: ['DecisionEvent'],
    direction: 'INITIATES points from the initiating actor to the decision event.',
    cardinality: 'MANY_TO_ONE',
    allowsTemporalOverlap: false,
    requiresEvidence: false,
    minimumConfidence: null,
    lapemoSourceOfTruth: null,
    notes: '',
  },
  {
    edgeType: 'MAKES',
    allowedSourceTypes: ['Person', 'Agent'],
    allowedTargetTypes: ['DecisionEvent'],
    direction: 'MAKES points from the final deciding actor to the decision event.',
    cardinality: 'EXACTLY_ONE_ACTIVE_INBOUND',
    allowsTemporalOverlap: false,
    requiresEvidence: false,
    minimumConfidence: null,
    lapemoSourceOfTruth: { Agent: 'DecisionRecord.executedById with executedByType', Person: 'DecisionRecord.executedById with executedByType' },
    notes: 'Exactly one final actor per decision event.',
  },
  {
    edgeType: 'INSTANCE_OF',
    allowedSourceTypes: ['DecisionEvent'],
    allowedTargetTypes: ['DecisionType'],
    direction: 'INSTANCE_OF points from the decision event to its decision type.',
    cardinality: 'MANY_TO_ONE',
    allowsTemporalOverlap: false,
    requiresEvidence: false,
    minimumConfidence: null,
    lapemoSourceOfTruth: { DecisionEvent: 'DecisionRecord.decisionTypeId' },
    notes: '',
  },
  {
    edgeType: 'AUTHORIZED_BY',
    allowedSourceTypes: ['DecisionEvent', 'ActionEvent'],
    allowedTargetTypes: ['AuthorityGrant'],
    direction: 'AUTHORIZED_BY points from the event to the authority grant that permitted it.',
    cardinality: 'MANY_TO_ONE',
    allowsTemporalOverlap: false,
    requiresEvidence: false,
    minimumConfidence: null,
    lapemoSourceOfTruth: null,
    notes: 'Graph canonical. DecisionRecord.authorityInvokedId is a String with no foreign key and no target model, and is deliberately not written by this package. See IB-004.',
  },
  {
    edgeType: 'GOVERNED_BY',
    allowedSourceTypes: ['DecisionEvent', 'DecisionType', 'Agent'],
    allowedTargetTypes: ['Policy'],
    direction: 'GOVERNED_BY points from the governed node to the policy governing it.',
    cardinality: 'MANY_TO_MANY',
    allowsTemporalOverlap: true,
    requiresEvidence: false,
    minimumConfidence: null,
    lapemoSourceOfTruth: null,
    notes: '',
  },
  {
    edgeType: 'CHECKED_BY',
    allowedSourceTypes: ['DecisionEvent', 'DecisionType'],
    allowedTargetTypes: ['Control'],
    direction: 'CHECKED_BY points from the checked node to the control that checks it.',
    cardinality: 'MANY_TO_MANY',
    allowsTemporalOverlap: true,
    requiresEvidence: false,
    minimumConfidence: null,
    lapemoSourceOfTruth: { DecisionType: 'GovernanceControl.decisionTypeId and agentScope' },
    notes: '',
  },
  {
    edgeType: 'USES',
    allowedSourceTypes: ['DecisionEvent', 'Agent'],
    allowedTargetTypes: ['InformationAsset'],
    direction: 'USES points from the consuming node to the information asset consumed.',
    cardinality: 'MANY_TO_MANY',
    allowsTemporalOverlap: true,
    requiresEvidence: false,
    minimumConfidence: null,
    lapemoSourceOfTruth: null,
    notes: 'Generic name, explicit node pairs. Information consumption only.',
  },
  {
    edgeType: 'SUPPORTED_BY',
    allowedSourceTypes: ['DecisionEvent', 'AuthorityGrant', 'AutonomyState'],
    allowedTargetTypes: ['EvidenceObject'],
    direction: 'SUPPORTED_BY points from the asserted node to the evidence supporting it.',
    cardinality: 'MANY_TO_MANY',
    allowsTemporalOverlap: true,
    requiresEvidence: false,
    minimumConfidence: null,
    lapemoSourceOfTruth: null,
    notes: '',
  },
  {
    edgeType: 'PRODUCES',
    allowedSourceTypes: ['DecisionEvent', 'ActionEvent'],
    allowedTargetTypes: ['Outcome'],
    direction: 'PRODUCES points from the event to the outcome it produced.',
    cardinality: 'MANY_TO_MANY',
    allowsTemporalOverlap: true,
    requiresEvidence: false,
    minimumConfidence: null,
    lapemoSourceOfTruth: null,
    notes: '',
  },
  {
    edgeType: 'PERFORMS',
    allowedSourceTypes: ['Agent', 'Person'],
    allowedTargetTypes: ['ActionEvent'],
    direction: 'PERFORMS points from the acting actor to the action event.',
    cardinality: 'MANY_TO_ONE',
    allowsTemporalOverlap: false,
    requiresEvidence: false,
    minimumConfidence: null,
    lapemoSourceOfTruth: null,
    notes: 'QRY-002 traverses this edge in reverse to reach the actor.',
  },
  {
    edgeType: 'EXECUTED_IN',
    allowedSourceTypes: ['ActionEvent'],
    allowedTargetTypes: ['EnterpriseSystem'],
    direction: 'EXECUTED_IN points from the action event to the system it ran in.',
    cardinality: 'MANY_TO_ONE',
    allowsTemporalOverlap: false,
    requiresEvidence: false,
    minimumConfidence: null,
    lapemoSourceOfTruth: null,
    notes: '',
  },
  {
    edgeType: 'INVOKES',
    allowedSourceTypes: ['DecisionEvent', 'ActionEvent'],
    allowedTargetTypes: ['EnterpriseSystem'],
    direction: 'INVOKES points from the event to the system it calls.',
    cardinality: 'MANY_TO_MANY',
    allowsTemporalOverlap: true,
    requiresEvidence: false,
    minimumConfidence: null,
    lapemoSourceOfTruth: null,
    notes: 'Substrate for the system-scope check in AUTH-003 and the comparison in AUTH-005.',
  },
  {
    edgeType: 'MODIFIES',
    allowedSourceTypes: ['ActionEvent'],
    allowedTargetTypes: ['InformationAsset', 'EnterpriseSystem'],
    direction: 'MODIFIES points from the action event to what it changed.',
    cardinality: 'MANY_TO_MANY',
    allowsTemporalOverlap: true,
    requiresEvidence: false,
    minimumConfidence: null,
    lapemoSourceOfTruth: null,
    notes: '',
  },
  {
    edgeType: 'RESULTS_IN',
    allowedSourceTypes: ['DecisionEvent'],
    allowedTargetTypes: ['ActionEvent'],
    direction: 'RESULTS_IN points from the decision event to the action it caused.',
    cardinality: 'MANY_TO_MANY',
    allowsTemporalOverlap: true,
    requiresEvidence: false,
    minimumConfidence: null,
    lapemoSourceOfTruth: null,
    notes: '',
  },
  {
    edgeType: 'ESCALATED_TO',
    allowedSourceTypes: ['DecisionEvent'],
    allowedTargetTypes: ['Person', 'Role'],
    direction: 'ESCALATED_TO points from the decision event to the escalation target.',
    cardinality: 'MANY_TO_MANY',
    allowsTemporalOverlap: true,
    requiresEvidence: false,
    minimumConfidence: null,
    lapemoSourceOfTruth: { DecisionEvent: 'EscalationPath tiers' },
    notes: '',
  },
  {
    edgeType: 'REVIEWS',
    allowedSourceTypes: ['Person'],
    allowedTargetTypes: ['DecisionEvent'],
    direction: 'REVIEWS points from the reviewing Person to the decision event reviewed.',
    cardinality: 'MANY_TO_MANY',
    allowsTemporalOverlap: true,
    requiresEvidence: false,
    minimumConfidence: null,
    lapemoSourceOfTruth: null,
    notes: 'Substrate for AUTH-008.',
  },
  {
    edgeType: 'VALIDATES',
    allowedSourceTypes: ['Control'],
    allowedTargetTypes: ['DecisionEvent', 'Outcome'],
    direction: 'VALIDATES points from the control to what it validated.',
    cardinality: 'MANY_TO_MANY',
    allowsTemporalOverlap: true,
    requiresEvidence: false,
    minimumConfidence: null,
    lapemoSourceOfTruth: null,
    notes: '',
  },

  // ── Information and evidence ──────────────────────────────────────────────
  {
    edgeType: 'SOURCED_FROM',
    allowedSourceTypes: ['InformationAsset', 'EvidenceObject'],
    allowedTargetTypes: ['EnterpriseSystem'],
    direction: 'SOURCED_FROM points from the asset to the system it came from.',
    cardinality: 'MANY_TO_ONE',
    allowsTemporalOverlap: false,
    requiresEvidence: false,
    minimumConfidence: null,
    lapemoSourceOfTruth: { InformationAsset: 'ExternalEntityMapping', EvidenceObject: 'ExternalEntityMapping' },
    notes: '',
  },
  {
    edgeType: 'AUTHORITATIVE_FOR',
    allowedSourceTypes: ['InformationAsset', 'EnterpriseSystem'],
    allowedTargetTypes: ['InformationAsset'],
    direction: 'AUTHORITATIVE_FOR points from the authoritative source to what it is authoritative for.',
    cardinality: 'MANY_TO_MANY',
    allowsTemporalOverlap: true,
    requiresEvidence: false,
    minimumConfidence: null,
    lapemoSourceOfTruth: { InformationAsset: 'KnowledgeDomain.primarySourceNodeId', EnterpriseSystem: 'KnowledgeDomain.primarySourceNodeId' },
    notes: 'Substrate for the NON_AUTHORITATIVE_SOURCE check in AUTH-009.',
  },
  {
    edgeType: 'DERIVED_FROM_EVIDENCE',
    allowedSourceTypes: ['InformationAsset'],
    allowedTargetTypes: ['EvidenceObject'],
    direction: 'DERIVED_FROM_EVIDENCE points from the derived asset to the evidence it came from.',
    cardinality: 'MANY_TO_MANY',
    allowsTemporalOverlap: true,
    requiresEvidence: false,
    minimumConfidence: null,
    lapemoSourceOfTruth: null,
    notes: 'A stored artifact with lineage outranks a derived copy without lineage. See ADR-005.',
  },
  {
    edgeType: 'GENERATES',
    allowedSourceTypes: ['Agent', 'Person', 'EnterpriseSystem'],
    allowedTargetTypes: ['EvidenceObject', 'InformationAsset'],
    direction: 'GENERATES points from the producer to what it produced.',
    cardinality: 'MANY_TO_MANY',
    allowsTemporalOverlap: true,
    requiresEvidence: false,
    minimumConfidence: null,
    lapemoSourceOfTruth: null,
    notes: '',
  },
  {
    edgeType: 'VERIFIED_BY',
    allowedSourceTypes: ['EvidenceObject', 'InformationAsset'],
    allowedTargetTypes: ['Person', 'Control'],
    direction: 'VERIFIED_BY points from the verified artifact to its verifier.',
    cardinality: 'MANY_TO_MANY',
    allowsTemporalOverlap: true,
    requiresEvidence: false,
    minimumConfidence: null,
    lapemoSourceOfTruth: null,
    notes: '',
  },
]

const CONTRACTS_BY_TYPE = new Map<EdgeType, RelationshipContract>(
  RELATIONSHIP_CONTRACTS.map((contract) => [contract.edgeType, contract]),
)

export function relationshipContract(edgeType: EdgeType): RelationshipContract {
  const contract = CONTRACTS_BY_TYPE.get(edgeType)
  if (!contract) throw new Error(`No relationship contract registered for edge type ${edgeType}`)
  return contract
}

/** Every declared edge type has exactly one contract, and vice versa. */
export function edgeTypesWithoutContract(): EdgeType[] {
  return EDGE_TYPES.filter((edgeType) => !CONTRACTS_BY_TYPE.has(edgeType))
}

/** Edge types with at least one source type whose relationship Lapemo owns. */
export function projectedEdgeTypes(): EdgeType[] {
  return RELATIONSHIP_CONTRACTS.filter(
    (c) => c.lapemoSourceOfTruth !== null && Object.keys(c.lapemoSourceOfTruth).length > 0,
  ).map((c) => c.edgeType)
}

/** Edge types with no Lapemo owner for any source type, canonical in this graph. */
export function graphCanonicalEdgeTypes(): EdgeType[] {
  return RELATIONSHIP_CONTRACTS.filter(
    (c) => c.lapemoSourceOfTruth === null || Object.keys(c.lapemoSourceOfTruth).length === 0,
  ).map((c) => c.edgeType)
}

/** Resolve the owning Lapemo record for one concrete source type, or null. */
export function lapemoOwnerFor(edgeType: EdgeType, fromNodeType: NodeType): string | null {
  return relationshipContract(edgeType).lapemoSourceOfTruth?.[fromNodeType] ?? null
}
